services:
  - type: web
    name: indonavv-backend
    env: docker
    region: singapore
    plan: free
    dockerContext: .
    dockerfilePath: backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
