package com.example.indonavv.ui.theme

import androidx.compose.ui.graphics.Color

// Light Scheme Colors
val primaryLight = Color(0xFF005AC1)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD8E2FF)
val onPrimaryContainerLight = Color(0xFF001A41)
val secondaryLight = Color(0xFF006A6A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9CF1F0)
val onSecondaryContainerLight = Color(0xFF002020)
val tertiaryLight = Color(0xFF984061)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD9E2)
val onTertiaryContainerLight = Color(0xFF3E001D)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEFBFF)
val onBackgroundLight = Color(0xFF1B1B1F)
val surfaceLight = Color(0xFFFEFBFF)
val onSurfaceLight = Color(0xFF1B1B1F)
val surfaceVariantLight = Color(0xFFE1E2EC)
val onSurfaceVariantLight = Color(0xFF44474F)
val outlineLight = Color(0xFF74777F)

// Dark Scheme Colors
val primaryDark = Color(0xFFAEC6FF)
val onPrimaryDark = Color(0xFF002E6C)
val primaryContainerDark = Color(0xFF004494)
val onPrimaryContainerDark = Color(0xFFD8E2FF)
val secondaryDark = Color(0xFF80D5D4)
val onSecondaryDark = Color(0xFF003737)
val secondaryContainerDark = Color(0xFF004F4F)
val onSecondaryContainerDark = Color(0xFF9CF1F0)
val tertiaryDark = Color(0xFFFFB1C8)
val onTertiaryDark = Color(0xFF5E1133)
val tertiaryContainerDark = Color(0xFF7B2949)
val onTertiaryContainerDark = Color(0xFFFFD9E2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1B1B1F)
val onBackgroundDark = Color(0xFFE3E2E6)
val surfaceDark = Color(0xFF1B1B1F)
val onSurfaceDark = Color(0xFFE3E2E6)
val surfaceVariantDark = Color(0xFF44474F)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
